Techdebt/add spaces inside parens
sarahsturgeon/cfc_factions_3 pull request #45
Opened 2019-09-30 21:14 UTC by sarahsturgeon

2019-09-30 21:32 UTC, sarahsturgeon reviewed
Fixes

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/cl_utilities.lua
> +                    MaxSize = ( (#babypanel:GetText() ) * mulmod)
```suggestion
                    MaxSize = ( ( #babypanel:GetText() ) * mulmod )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_alertsderma.lua
> +            main_panel.logview:AddLine(logs.Time, logs.Message,printyprint( logs.Type) )
```suggestion
            main_panel.logview:AddLine( logs.Time, logs.Message,printyprint( logs.Type) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_creditsderma.lua
> +    self.TextBox:SetColor( Color(0,0,0,255) )
```suggestion
    self.TextBox:SetColor( Color( 0, 0, 0, 255 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.BottomPanel:SetBackgroundColor( Color(0,0,0,0) )
```suggestion
    self.BottomPanel:SetBackgroundColor( Color(0, 0, 0, 0) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.BottomPanel:SetBackgroundColor( ColorAlpha(cfg.ColorSchemes.BackgroundPanel,255) )
```suggestion
    self.BottomPanel:SetBackgroundColor( ColorAlpha( cfg.ColorSchemes.BackgroundPanel, 255 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.BottomContainerTop:SetBackgroundColor( ColorAlpha(cfg.ColorSchemes.BackgroundPanel,255) )
```suggestion
    self.BottomContainerTop:SetBackgroundColor( ColorAlpha( cfg.ColorSchemes.BackgroundPanel, 255 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.BottomContainerBottom:SetBackgroundColor( ColorAlpha(cfg.ColorSchemes.BackgroundPanel,255) )
```suggestion
    self.BottomContainerBottom:SetBackgroundColor( ColorAlpha( cfg.ColorSchemes.BackgroundPanel, 255 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.BottomButtonsControlPanel:SetBackgroundColor( ColorAlpha(cfg.ColorSchemes.BackgroundPanel,255) )
```suggestion
    self.BottomButtonsControlPanel:SetBackgroundColor( ColorAlpha( cfg.ColorSchemes.BackgroundPanel, 255 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.ButtonsContainer:SetBackgroundColor( ColorAlpha(cfg.ColorSchemes.BackgroundPanel,255) )
```suggestion
    self.ButtonsContainer:SetBackgroundColor( ColorAlpha( cfg.ColorSchemes.BackgroundPanel, 255 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.ButtonsPanelLeft:SetBackgroundColor( ColorAlpha(cfg.ColorSchemes.BackgroundPanel,255) )
```suggestion
    self.ButtonsPanelLeft:SetBackgroundColor( ColorAlpha( cfg.ColorSchemes.BackgroundPanel, 255 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.ButtonsPanelRight:SetBackgroundColor( ColorAlpha(cfg.ColorSchemes.BackgroundPanel,255) )
```suggestion
    self.ButtonsPanelRight:SetBackgroundColor( ColorAlpha( cfg.ColorSchemes.BackgroundPanel, 255 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.ButtonsPanelLeft:SetWide( self.FirstPage:GetWide( ) + self.NextPage:GetWide( ) )
```suggestion
    self.ButtonsPanelLeft:SetWide( self.FirstPage:GetWide() + self.NextPage:GetWide() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    self.ButtonsPanelRight:SetWide( self.NextPage:GetWide( ) + self.LastPage:GetWide( ) )
```suggestion
    self.ButtonsPanelRight:SetWide( self.NextPage:GetWide() + self.LastPage:GetWide() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    self:SetPos( ( ( ScrW( ) / 2) - ( self:GetWide( ) / 2) ), ( (ScrH( ) / 2) - ( self:GetTall( ) / 2) ) )
```suggestion
    self:SetPos( ( ( ScrW( ) / 2 ) - ( self:GetWide() / 2 ) ), ( ( ScrH() / 2 ) - ( self:GetTall() / 2 ) ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    self.menubar:SetSize( self:GetWide( ) - 0.1, self:GetTall() - 745)
```suggestion
    self.menubar:SetSize( self:GetWide() - 0.1, self:GetTall() - 745 )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    self.container:SetSize( self:GetWide( ) - 20, self:GetTall() - 150)
```suggestion
    self.container:SetSize( self:GetWide() - 20, self:GetTall() - 150 )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    self.container:SetPos( (self:GetWide( ) / 2) - ( self.container:GetWide( ) / 2), 120)
```suggestion
    self.container:SetPos( ( self:GetWide() / 2 ) - ( self.container:GetWide() / 2 ), 120 )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    self.statusbar:SetSize( self:GetWide( ), self:GetTall( )-750 )
```suggestion
    self.statusbar:SetSize( self:GetWide(), self:GetTall() - 750 )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +        self.alertPanel:SetSize( self.container:GetWide( ), 55)
```suggestion
        self.alertPanel:SetSize( self.container:GetWide(), 55 )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    self.mainview:SetSize( self:GetWide( ) - 20, self:GetTall() - 230)
```suggestion
    self.mainview:SetSize( self:GetWide() - 20, self:GetTall() - 230 )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    self.mainview:SetPos( (self:GetWide( ) / 2) - ( self.mainview:GetWide( ) / 2), 120)
```suggestion
    self.mainview:SetPos( ( self:GetWide() / 2 ) - ( self.mainview:GetWide() / 2 ), 120 )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +        draw.SimpleText(string.format(cfg.DermaHeaderTitle, LocalPlayer( ):Nick() ), "CFC_Special", 5, 5, cfg.ColorSchemes.HeaderText)
```suggestion
        draw.SimpleText( string.format( cfg.DermaHeaderTitle, LocalPlayer():Nick() ), "CFC_Special", 5, 5, cfg.ColorSchemes.HeaderText ) 
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    mview:SetSize( self.mainview:GetWide( ), self.mainview:GetTall( ) )
```suggestion
    mview:SetSize( self.mainview:GetWide(), self.mainview:GetTall() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    Alert.ErrMsg:SetSize( Alert:GetWide( ), Alert:GetTall( ) )
```suggestion
    Alert.ErrMsg:SetSize( Alert:GetWide(), Alert:GetTall() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_newsderma.lua
> +    string.Replace( self.NewsBox:GetText( ), "%s", LocalPlayer( ):Nick() )
```suggestion
    string.Replace( self.NewsBox:GetText(), "%s", LocalPlayer():Nick() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/minis/cl_alertbox.lua
> +    self.MiniPanel:SetSize( self:GetWide( ), self:GetTall( ) )
```suggestion
    self.MiniPanel:SetSize( self:GetWide(), self:GetTall() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/minis/cl_alertbox.lua
> +    self.ErrMsg:SetColor(msgtype and msgtype ~= nil or Color( 255,0,0) )
```suggestion
    self.ErrMsg:SetColor( msgtype and msgtype ~= nil or Color( 255, 0, 0 ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_factionmanagment.lua
> +         cfcFactions:RemoveFaction(ply, ply:GetFactionID( ) )
```suggestion
         cfcFactions:RemoveFaction( ply, ply:GetFactionID() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_factions.lua
> +        if string.lower( string.Trim(v.Name) ) == string.lower( string.Trim(faction_name) ) then
```suggestion
        if string.lower( string.Trim( v.Name ) ) == string.lower( string.Trim( faction_name ) ) then
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_factions.lua
> +    for k, v in pairs(string.Explode("\n", cfcFactions:LoadNews( )) ) do
```suggestion
    for k, v in pairs( string.Explode( "\n", cfcFactions:LoadNews() ) ) do
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_init.lua
> +hook.Add("Initialize", "cfcInitializeFactions", cfcFactions:InitializeFactions( ) )
```suggestion
hook.Add( "Initialize", "cfcInitializeFactions", cfcFactions:InitializeFactions() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_init.lua
> +    for k, v in pairs(string.Explode("\n", cfcFactions:LoadNews( )) ) do
```suggestion
    for k, v in pairs( string.Explode( "\n", cfcFactions:LoadNews() ) ) do
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_init.lua
> +hook.Add("PlayerSpawn", "cfcPlayerSpawn", cfcPlayerSpawn( ply) )
```suggestion
hook.Add( "PlayerSpawn", "cfcPlayerSpawn", cfcPlayerSpawn( ply ) )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_permsys.lua
> +    print("Authenticating user " .. player:SteamID( ) )
```suggestion
    print( "Authenticating user " .. player:SteamID() )
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_permsys.lua
> +    if not IsValid( player ) or not player:IsPlayer() then print("Unable to add permission, invalid player") return false end
```suggestion
    if not IsValid( player ) or not player:IsPlayer() then print( "Unable to add permission, invalid player" ) return false end
```

2019-09-30 21:32 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_permsys.lua
> +hook.Add("Initialize", "cfcInitializeUsers", fpm:authAllUsers( ) )
```suggestion
hook.Add( "Initialize", "cfcInitializeUsers", fpm:authAllUsers() )
```

2019-09-30 21:57 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    self.closeButton:SetPos( self:GetWide( ) - 35, 5)
```suggestion
    self.closeButton:SetPos( self:GetWide() - 35, 5 )
```

2019-10-01 00:22 UTC, justinmuskopf commented on lua/cfcfactions/core/sh/sh_sharedutils.lua
> +    return os.date( "%H:%M:%S - %d/%m/%Y", os.time( ) )
```suggestion
    return os.date( "%H:%M:%S - %d/%m/%Y", os.time() )
```

2019-10-01 00:28 UTC, justinmuskopf commented on lua/cfcfactions/core/sv/sv_users.lua
> +	if table.HasValue(cfcuser, user:SteamID64( ) ) then
```suggestion
	if table.HasValue(cfcuser, user:SteamID64() ) then
```

2019-10-01 00:28 UTC, justinmuskopf requested changes
pls

2019-10-01 00:50 UTC, sarahsturgeon commented
Closing this in favor of https://github.com/brandonsturgeon/cfc_factions_3/pull/46

( :( )

2019-10-01 00:50 UTC, closed without merging