Cl userderma net #188
sarahsturgeon/cfc_factions_3 pull request #60
Opened 2019-10-29 20:59 UTC by samuelWilliams99

Wire cl_userderma to net messages, card #188

2019-11-01 08:10 UTC, sarahsturgeon requested changes
We'll need to wait until V's big PR is merged, then deal with conflicts here, before merging

2019-11-03 02:54 UTC, justinmuskopf requested changes
I need to revisit this, brb

2019-11-03 02:54 UTC, justinmuskopf commented on lua/cfcfactions/core/cl/dermas/cl_usersderma.lua
> +local cfcusers = {}
`local factioneers = {}`

2019-11-03 02:54 UTC, justinmuskopf commented on lua/cfcfactions/core/cl/dermas/cl_usersderma.lua
> +local cfcusers = {}
(And propagate to the rest of the file, of course)

2019-11-03 02:54 UTC, justinmuskopf commented on lua/cfcfactions/core/cl/dermas/cl_usersderma.lua
>  local Panel = {}
```suggestion
local ViewUserDerma = {}
```
Or something like that?
@brandonsturgeon ideas?

2019-11-22 21:04 UTC, samuelWilliams99 commented on lua/cfcfactions/core/cl/dermas/cl_usersderma.lua
> +local cfcusers = {}
I've changed this for cl_usersderma and sv_users, not sure if you wanted me to also do sv_users, please take a look.

2019-11-24 23:13 UTC, sarahsturgeon commented
Tested on CFC Test server with no errors and expected print output

2019-12-09 00:01 UTC, ghost requested changes
Minor changes

2019-12-09 00:01 UTC, ghost commented on lua/cfcfactions/core/cl/dermas/cl_usersderma.lua
> -cfcFactions:RegisterDermaMenu( "View Users", Panel, 1 )
This needs to be undone (for now) since its used to register it to the menubar. Its messy but it works, for now.

2019-12-09 00:15 UTC, samuelWilliams99 commented on lua/cfcfactions/core/cl/dermas/cl_usersderma.lua
> -cfcFactions:RegisterDermaMenu( "View Users", Panel, 1 )
You want to keep `cfcFactions:RegisterDermaMenu( "View Users", Panel, 1 )`?

2019-12-09 00:16 UTC, ghost commented on lua/cfcfactions/core/cl/dermas/cl_usersderma.lua
> -cfcFactions:RegisterDermaMenu( "View Users", Panel, 1 )
Yes, for now. Part of my work is redoing that to its no longer needed. Its stupidly messy and overly complex

2019-12-09 00:19 UTC, samuelWilliams99 commented
Is this finally ready for merge?

2019-12-09 00:21 UTC, ghost commented
> 
> 
> Is this finally ready for merge?

Was this tested? It may not be testable till we incorporate [Bleck's UI](https://github.com/brandonsturgeon/cfc_factions_3/pull/70). Not that big of a deal + we can refine it as we go.

2019-12-09 00:25 UTC, samuelWilliams99 commented
> > Is this finally ready for merge?
> 
> Was this tested? It may not be testable till we incorporate [Bleck's UI](https://github.com/brandonsturgeon/cfc_factions_3/pull/70). Not that big of a deal + we can refine it as we go.

We ran it on a test server and printed the table on client when it was received, all seemed fine

2019-12-09 00:29 UTC, ghost commented
All good then

2019-12-09 00:29 UTC, merged