Various whitespace fixes
sarahsturgeon/cfc_factions_3 pull request #76
Opened 2020-01-05 09:02 UTC by sarahsturgeon

2020-01-06 17:46 UTC, ghost submitted a review, later dismissed
Looks good to me 👍

2020-01-06 18:05 UTC, sarahsturgeon commented on lua/cfcfactions/core/cl/dermas/cl_mainderma.lua
> +    local posX = ( ScrW() / 2 ) - ( self:GetWidt() / 2)
```suggestion
    local posX = ( ScrW() / 2 ) - ( self:GetWide() / 2)
```

2020-01-06 22:29 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_factions.lua
> +    if not type( EditName ) == "string" then
```suggestion
    if type( EditName ) ~= "string" then
```

2020-01-06 22:29 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_factions.lua
> +
```suggestion
```

2020-01-06 22:29 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_factions.lua
> +
```suggestion
```

2020-01-06 22:29 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_factions.lua
> +                -- TODO Change to SetUserFaction instead of RemoveUser
```suggestion
            -- TODO Change to SetUserFaction instead of RemoveUser
```

2020-01-06 22:29 UTC, sarahsturgeon commented on lua/cfcfactions/core/sv/sv_factions.lua
> +                -- RemoveUser completely wipes their data.
```suggestion
            -- RemoveUser completely wipes their data. 
```

2020-01-10 20:42 UTC, ghost requested changes

2020-01-10 20:42 UTC, ghost commented on lua/cfcfactions/core/cl/dermas/cl_factionsderma.lua
> +    local killDeathRatio = Factions.Kills .. "/" .. Faction.Deaths
```suggestion
    local killDeathRatio = Faction.Kills .. "/" .. Faction.Deaths
```

2020-01-10 22:33 UTC, ghost submitted a review, later dismissed
Looks good to me 👍

2020-01-11 23:18 UTC, justinmuskopf submitted a review, later dismissed
Basic consideration comments, but nothing blocking that I saw.

2020-01-11 23:18 UTC, justinmuskopf commented on lua/cfcfactions/core/sv/sv_factions.lua
> +    factionDescription = TrimStringSize( factionDescription, 255 )
perhaps we aren't worried about this, but these could all be config params?

2020-01-11 23:18 UTC, justinmuskopf commented on lua/cfcfactions/core/sv/sv_factions.lua
> +    -- Need to check if player ( If NOT a admin, or NOT a dev ), is in the faction )
```suggestion
    -- Need to check if player ( If NOT an admin, or NOT a dev ), is in the faction )
```

lol jk

2020-01-11 23:18 UTC, justinmuskopf commented on lua/cfcfactions/core/sv/sv_logging.lua
> -end
👍

2020-01-11 23:18 UTC, justinmuskopf commented on lua/cfcfactions/core/sv/sv_mysql.lua
>              )
We might want to store all of the DB creation stuff in a `.sql` file or something

2020-01-11 23:22 UTC, justinmuskopf approved these changes
Nice!

2020-01-11 23:22 UTC, merged